// Code generated by mockery v2.53.3. DO NOT EDIT.

package session

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// mockCasClient is an autogenerated mock type for the casClient type
type mockCasClient struct {
	mock.Mock
}

type mockCasClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCasClient) EXPECT() *mockCasClient_Expecter {
	return &mockCasClient_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function with given fields: w, r
func (_m *mockCasClient) Logout(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// mockCasClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type mockCasClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *mockCasClient_Expecter) Logout(w interface{}, r interface{}) *mockCasClient_Logout_Call {
	return &mockCasClient_Logout_Call{Call: _e.mock.On("Logout", w, r)}
}

func (_c *mockCasClient_Logout_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *mockCasClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *mockCasClient_Logout_Call) Return() *mockCasClient_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockCasClient_Logout_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *mockCasClient_Logout_Call {
	_c.Run(run)
	return _c
}

// newMockCasClient creates a new instance of mockCasClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCasClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCasClient {
	mock := &mockCasClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
