// Code generated by mockery v2.53.3. DO NOT EDIT.

package casfilter

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// mockCasBrowserClient is an autogenerated mock type for the casBrowserClient type
type mockCasBrowserClient struct {
	mock.Mock
}

type mockCasBrowserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCasBrowserClient) EXPECT() *mockCasBrowserClient_Expecter {
	return &mockCasBrowserClient_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: nextHandler
func (_m *mockCasBrowserClient) Handle(nextHandler http.Handler) http.Handler {
	ret := _m.Called(nextHandler)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(nextHandler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// mockCasBrowserClient_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type mockCasBrowserClient_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - nextHandler http.Handler
func (_e *mockCasBrowserClient_Expecter) Handle(nextHandler interface{}) *mockCasBrowserClient_Handle_Call {
	return &mockCasBrowserClient_Handle_Call{Call: _e.mock.On("Handle", nextHandler)}
}

func (_c *mockCasBrowserClient_Handle_Call) Run(run func(nextHandler http.Handler)) *mockCasBrowserClient_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *mockCasBrowserClient_Handle_Call) Return(_a0 http.Handler) *mockCasBrowserClient_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCasBrowserClient_Handle_Call) RunAndReturn(run func(http.Handler) http.Handler) *mockCasBrowserClient_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCasBrowserClient creates a new instance of mockCasBrowserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCasBrowserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCasBrowserClient {
	mock := &mockCasBrowserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
